export const authConstants = {
  CLEAR_MESSAGES_AUTHENTICATION: "CLEAR_MESSAGES_AUTHENTICATION",
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",
  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE: "SIGNOUT_FAILURE"
}

export const pageConstants = {
  PAGE_REQUEST: "PAGE_REQUEST"
}

export const cartConstants = {
  CART_REQUEST: "CART_REQUEST",
  CART_SUCCESS: "CART_SUCCESS",
  CART_FAILURE: "CART_FAILURE",
  CLEARMESSAGES_CART: "CLEARMESSAGES_CART"
}