  
// AUTHENTICATION
export const AUTHENTICATION_FETCH = 'AUTHENTICATION_FETCH'
export const AUTHENTICATION_SUCESS = 'AUTHENTICATION_SUCESS'
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE'

export const authConstants = {
  AUTHENTICATION_REQUEST: "AUTHENTICATION_REQUEST",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAILURE: "AUTHENTICATION_FAILURE"
}